export const occupations = [
  "Accountant",
  "Actor",
  "Actuary",
  "Architect",
  "Artist",
  "Astronomer",
  "Attorney",
  "Author",
  "Baker",
  "Barber",
  "Bartender",
  "Biologist",
  "Butcher",
  "Carpenter",
  "Chef",
  "Chemist",
  "Civil Engineer",
  "Coach",
  "Consultant",
  "Dancer",
  "Data Scientist",
  "Dentist",
  "Designer",
  "Developer",
  "Doctor",
  "Economist",
  "Editor",
  "Electrician",
  "Engineer",
  "Entrepreneur",
  "Farmer",
  "Filmmaker",
  "Financial Advisor",
  "Firefighter",
  "Florist",
  "Geologist",
  "Graphic Designer",
  "Hairstylist",
  "Historian",
  "Human Resources Manager",
  "Illustrator",
  "Interior Designer",
  "Inventor",
  "Investigator",
  "IT Professional",
  "Janitor",
  "Journalist",
  "Judge",
  "Lawyer",
  "Librarian",
  "Linguist",
  "Machinist",
  "Manager",
  "Marketer",
  "Mathematician",
  "Mechanic",
  "Meteorologist",
  "Military Officer",
  "Musician",
  "Neurologist",
  "Nurse",
  "Nutritionist",
  "Occupational Therapist",
  "Optician",
  "Painter",
  "Paramedic",
  "Pharmacist",
  "Photographer",
  "Physician",
  "Physicist",
  "Pilot",
  "Plumber",
  "Police Officer",
  "Politician",
  "Professor",
  "Programmer",
  "Project Manager",
  "Psychiatrist",
  "Psychologist",
  "Real Estate Agent",
  "Receptionist",
  "Researcher",
  "Sailor",
  "Salesperson",
  "Scientist",
  "Secretary",
  "Singer",
  "Social Worker",
  "Software Engineer",
  "Statistician",
  "Surgeon",
  "Tailor",
  "Teacher",
  "Technician",
  "Therapist",
  "Trader",
  "Translator",
  "Travel Agent",
  "Truck Driver",
  "Urban Planner",
  "Veterinarian",
  "Videographer",
  "Waiter",
  "Web Designer",
  "Web Developer",
  "Welder",
  "Writer",
  "Zoologist",
  "Other"
].map(o => ({ label: o, value: o }));
